from pathlib import Path
ASSETS_DIR = Path(__file__).parent / "assets"

EVENTS = [
    {
        "id": "navratri",
        "name": "Navratri Pooja",
        "description": "Celebrate Navratri with devotion and music.",
        "date": "2025-10-10 18:00",
        "location": "Community Hall, Ludhiana",
        "price": 299,
        "total_tickets": 150,
        "available_tickets": 150,
        "check_ins": 0,
        "image": "navratri.jpeg.avif",
    },
    {
        "id": "diwali",
        "name": "Diwali Dance Night",
        "description": "A night of lights, dance and celebration.",
        "date": "2025-11-12 20:00",
        "location": "City Club, Ludhiana",
        "price": 399,
        "total_tickets": 200,
        "available_tickets": 200,
        "check_ins": 0,
        "image": "diwali.jpeg",
    },
    {
        "id": "freshers",
        "name": "Freshers Bash",
        "description": "Welcome party for all freshers!",
        "date": "2025-10-20 19:00",
        "location": "University Auditorium",
        "price": 199,
        "total_tickets": 120,
        "available_tickets": 120,
        "check_ins": 0,
        "image": "freshers.jpeg",
    },
    {
        "id": "ravan",
        "name": "Ravan Dahan",
        "description": "Witness the grand Dussehra celebration.",
        "date": "2025-10-24 18:30",
        "location": "Main Ground",
        "price": 99,
        "total_tickets": 500,
        "available_tickets": 500,
        "check_ins": 0,
        "image": "ravan.jpeg",
    },
    {
        "id": "club",
        "name": "Club Night",
        "description": "DJ, drinks and dance till late!",
        "date": "2025-12-31 21:00",
        "location": "Downtown Club",
        "price": 499,
        "total_tickets": 100,
        "available_tickets": 100,
        "check_ins": 0,
        "image": "club.jpeg",
    },
]
