# events_data.py

EVENTS = [
    {
        "id": 1,
        "name": "Navratri Garba Night",
        "description": "Celebrate Navratri with vibrant dances and traditional music. Dress in colorful attire and join the festivities!",
        "date_time": "2025-10-12 19:00",
        "venue": "City Cultural Hall, Ludhiana",
        "total_tickets": 100,
        "price": 500,
        "image": "navratri.jpeg.avif",
    },
    {
        "id": 2,
        "name": "Diwali Dance Celebration",
        "description": "A spectacular Diwali night filled with dance, music, and fireworks. Bring your friends and family!",
        "date_time": "2025-11-01 18:30",
        "venue": "Town Square Auditorium",
        "total_tickets": 120,
        "price": 600,
        "image": "diwali.jpeg",
    },
    {
        "id": 3,
        "name": "Freshers Welcome Party",
        "description": "Kick off the semester with fun, games, and music. Meet your peers and enjoy an unforgettable night!",
        "date_time": "2025-09-20 20:00",
        "venue": "University Campus Lawn",
        "total_tickets": 150,
        "price": 400,
        "image": "freshers.jpeg",
    },
    {
        "id": 4,
        "name": "Summer Music Fest",
        "description": "An outdoor festival featuring live bands, food stalls, and fun activities for all music lovers!",
        "date_time": "2025-06-15 16:00",
        "venue": "Green Park Amphitheatre",
        "total_tickets": 200,
        "price": 800,
        "image": "club.jpeg",
    },
    {
        "id": 5,
        "name": "Art Exhibition",
        "description": "Showcasing local artists and their masterpieces. Explore, admire, and buy artwork from talented creators.",
        "date_time": "2025-07-10 10:00",
        "venue": "City Art Gallery",
        "total_tickets": 80,
        "price": 300,
        "image": "ravan.jpeg",
    },
    {
        "id": 6,
        "name": "Tech Conference",
        "description": "Join industry leaders and innovators to discuss the latest in technology and entrepreneurship.",
        "date_time": "2025-08-05 09:00",
        "venue": "Tech Convention Center",
        "total_tickets": 250,
        "price": 1000,
        "image": "tech.jpeg",
    },
]
