# events_data.py

EVENTS = [
    {
        "id": 1,
        "name": "Navratri Garba Night",
        "image": "navratri.jpeg.avif",
        "description": "Celebrate the festive season with Garba and Dandiya.",
        "date": "2025-10-10 07:00 PM",
        "location": "Cultural Hall, City Center",
        "price": 300,
        "total_tickets": 200,
    },
    {
        "id": 2,
        "name": "Diwali Dance Celebration",
        "image": "diwali.jpeg",
        "description": "Dance the night away with lights and music.",
        "date": "2025-11-01 08:00 PM",
        "location": "Grand Ballroom, Star Hotel",
        "price": 400,
        "total_tickets": 150,
    },
    {
        "id": 3,
        "name": "Freshers Welcome Party",
        "image": "freshers.jpeg",
        "description": "Kickstart the college journey with fun and friends.",
        "date": "2025-07-15 06:00 PM",
        "location": "University Ground",
        "price": 200,
        "total_tickets": 250,
    },
    {
        "id": 4,
        "name": "Club Night Extravaganza",
        "image": "club.jpeg",
        "description": "An electrifying club night experience.",
        "date": "2025-08-20 09:00 PM",
        "location": "Downtown Club",
        "price": 500,
        "total_tickets": 100,
    },
    {
        "id": 5,
        "name": "Ravan Dahan Event",
        "image": "ravan.jpeg",
        "description": "Celebrate Dussehra with the grand Ravan Dahan.",
        "date": "2025-10-24 07:00 PM",
        "location": "Open Grounds, City Center",
        "price": 250,
        "total_tickets": 300,
    },
]
